version: '3'

services:
  app:
    image: chatbot-meta:1.0 
    restart: on-failure 
    ports:
      - 3000:3000 
    environment: 
      - JWT_TOKEN=${JWT_TOKEN}
      - NUMBER_ID=${NUMBER_ID}
      - VERIFY_TOKEN=${VERIFY_TOKEN}